name: 🔨 pip-test
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest 
    environment: dev
    steps:
    - name: 'Set up Scoop'
      shell: pwsh
      run: |
        mkdir "C:\00PackageManager\"
        $env:SCOOP='C:\00PackageManager\Scoop'
        [Environment]::SetEnvironmentVariable('SCOOP', $env:SCOOP, 'User')
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser 
        iwr -useb get.scoop.sh | iex
        scoop bucket add extras
        scoop bucket add versions
        scoop bucket add nirsoft
        scoop bucket add java
        scoop bucket add nonportable
        
        echo "$env:SCOOP\shims" >> $env:GITHUB_PATH
        
    - name: Remove Python ENV (With Admin Rights)
      shell: powershell
      run: |
        # 创建一个临时脚本文件
        $scriptContent = @'
        # 修改系统 PATH
        $newPath = ([System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::Machine) -split ';' | Where-Object { 
          -not ($_ -like '*Python*') -and
          -not ($_ -like '*hostedtoolcache\windows\Python*')
        } | Where-Object { $_ -ne '' }) -join ';'
        
        # 设置新的系统 PATH
        [System.Environment]::SetEnvironmentVariable('Path', $newPath, [System.EnvironmentVariableTarget]::Machine)
        
        # 清理其他 Python 相关系统环境变量
        [System.Environment]::GetEnvironmentVariables([System.EnvironmentVariableTarget]::Machine).GetEnumerator() | 
        Where-Object { 
          $_.Name -like '*PYTHON*' -or 
          $_.Value -like '*Python*'
        } | ForEach-Object {
          [System.Environment]::SetEnvironmentVariable($_.Name, $null, [System.EnvironmentVariableTarget]::Machine)
        }
        
        Write-Host "Environment variables cleaned successfully"
        '@
        
        # 将脚本内容写入临时文件
        $scriptPath = Join-Path $env:TEMP "CleanupEnv.ps1"
        $scriptContent | Out-File -FilePath $scriptPath -Encoding UTF8
        
        # 以管理员权限运行脚本
        Start-Process powershell -ArgumentList "-ExecutionPolicy Bypass -File `"$scriptPath`"" -Verb RunAs -Wait
        
        # 清理临时脚本文件
        Remove-Item $scriptPath -Force

    - name: 'Install Required Tools'
      shell: pwsh 
      run: |
        scoop install -k git aria2 sudo 7zip
        scoop install -k python
        scoop cleanup *
        scoop cache rm *
        scoop cleanup -k *
        scoop list

    - name: 'Downloads Pip Packages'
      shell: pwsh
      run: |
        echo "C:\00PackageManager\Scoop\apps\python\current\Scripts" >> $GITHUB_PATH
        $env:SCOOPpy='C:\00PackageManager\Scoop\apps\python\current\python.exe'
        $env:PIP_USER=1
        & $env:SCOOPpy -m pip -V
        & $env:SCOOPpy -m pip install setuptools
        & $env:SCOOPpy -m pip install sqlmap bs4 XlsxWriter tqdm python-libnmap pyDes pipx openpyxl tldextract --no-warn-script-location
        & $env:SCOOPpy -m pip install colorama rncryptor pandas requests pycryptodome beautifulsoup4 chardet --no-warn-script-location
        git clone --depth 1 https://github.com/r0oth3x49/ghauri.git C:\00PackageManager\ghauri
        cd C:\00PackageManager\ghauri
        & $env:SCOOPpy -m pip install --upgrade -r requirements.txt
        tree /f
        & $env:SCOOPpy setup.py install
        & $env:SCOOPpy -m pip freeze

    - name: 'Compress Scoop Directory'
      shell: pwsh
      run: |
        & 'C:\00PackageManager\Scoop\apps\7zip\current\7z.exe' a -mx9 -t7z 'C:\00PackageManager.7z' 'C:\00PackageManager\*'
        & 'C:\00PackageManager\Scoop\apps\7zip\current\7z.exe' l 'C:\00PackageManager.7z'

    - name: 'Upload Compressed Scoop Directory'
      uses: actions/upload-artifact@v4
      with:
        name: Scoop-00PackageManager
        path: C:\00PackageManager.7z
        compression-level: 9 
        retention-days: 5
        
