name: 🔨 Scooparchive
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest 
    environment: dev
    steps:
    - name: 'Set up Scoop'
      shell: pwsh
      run: |
        mkdir "C:\00PackageManager\"
        $env:SCOOP='C:\00PackageManager\Scoop'
        [Environment]::SetEnvironmentVariable('SCOOP', $env:SCOOP, 'User')
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser 
        iwr -useb get.scoop.sh | iex
        scoop bucket add extras
        scoop bucket add versions
        scoop bucket add nirsoft
        scoop bucket add java
        scoop bucket add nonportable
        
        echo "$env:SCOOP\shims" >> $env:GITHUB_PATH

    - name: 'Cache Scoop Packages'
      uses: actions/cache@v4
      with:
        path: C:\00PackageManager\Scoop\cache
        key: ${{ runner.os }}-scoop-cache

    - name: 'Install Required Tools'
      shell: pwsh 
      run: |
        scoop install -k git aria2 sudo 7zip biome jq yq vim curl wget base64 gawk grep sed cwrsync cacert openssl
        scoop install -k liberica11-full-jdk liberica17-full-jdk liberica-full-jdk gradle maven jenv idea-ultimate jadx
        scoop install -k python
        scoop install -k codeql
        scoop install -k burp-suite-pro-np
        scoop install -k sublime-text vscode
        scoop install -k windowsdesktop-runtime-lts windows-terminal
        scoop install -k firefox-esr googlechrome
        scoop install -k dupeGuru dismplusplus renamer everything powertoys openark TrafficMonitor keepassxc kubectl
        scoop cleanup *
        scoop cache rm *
        scoop cleanup -k *
        scoop list

    - name: 'Downloads Pip Packages'
      shell: pwsh
      run: |
        echo "C:\00PackageManager\Scoop\apps\python\current\Scripts" >> $GITHUB_PATH
        & $env:SCOOPpy='C:\00PackageManager\Scoop\apps\python\current\python.exe'
        & $env:SCOOPpy -m pip install --upgrade pip
        & $env:SCOOPpy -m pip -V
        & $env:SCOOPpy -m pip install sqlmap bs4 XlsxWriter tqdm python-libnmap pyDes pipx openpyxl tldextract
        & $env:SCOOPpy -m pip install colorama rncryptor pandas requests pycryptodome beautifulsoup4 chardet
        git clone https://github.com/r0oth3x49/ghauri.git --depth 1
        cd ghauri
        & $env:SCOOPpy -m pip install --upgrade -r requirements.txt
        & $env:SCOOPpy setup.py install
        & $env:SCOOPpy -m pip freeze

    - name: 'Clone CodeQL Repository'
      shell: pwsh
      run: |
        git clone --depth 1 https://github.com/github/codeql.git C:\00PackageManager\CodeqlRules
        git clone --depth 1 https://github.com/github/vscode-codeql.git C:\00PackageManager\vscode-codeql
        tree /f C:\00PackageManager\codeqlRules

    - name: 'Compress Scoop Directory'
      shell: pwsh
      run: |
        & 'C:\00PackageManager\Scoop\apps\7zip\current\7z.exe' a -mx9 -t7z 'C:\00PackageManager.7z' 'C:\00PackageManager\*'
        & 'C:\00PackageManager\Scoop\apps\7zip\current\7z.exe' l 'C:\00PackageManager.7z'

    - name: 'Upload Compressed Scoop Directory'
      uses: actions/upload-artifact@v4
      with:
        name: Scoop-00PackageManager
        path: C:\00PackageManager.7z
        retention-days: 3
        ompression-level: 0
